### PR TITLE
Add a --autodetect option

### PR DESCRIPTION
**Pull request by jvoisin**
Instead of having to specify Kconfig file and /proc/cmdline, --autodetect will try to infer them.

This is related to #129

### CODE REVIEW

**Comment by a13xp0p0v** [comment]
It's a big nice feature that needs careful testing.
Let's return to this work after releasing a fresh version of kernel-hardening-checker.

**Comment by a13xp0p0v** [comment]
Hello @jvoisin,
The new version of the tool is released.
Would you like to restart this feature?
Thank you very much!

**Comment by jvoisin** [comment]
The red CI is unrelated to this PR

**Comment by a13xp0p0v** [comment]
Hello @jvoisin,

I've made some code refactoring to make your work easier (and the patch smaller):
https://github.com/a13xp0p0v/kernel-hardening-checker/commit/ae0e9b61a00b00b5157c1fc2781c5c4f3f6b3aab
https://github.com/a13xp0p0v/kernel-hardening-checker/commit/c577892112b1692ea53d251268d18217a18bf8a8
https://github.com/a13xp0p0v/kernel-hardening-checker/commit/0155202dbbacf5dab5002ef2a220bc58ae184172
https://github.com/a13xp0p0v/kernel-hardening-checker/commit/d6533504ff61a92145640c73f0d3c4a611330319
https://github.com/a13xp0p0v/kernel-hardening-checker/commit/df50315e63cdf13bfe111f74a81d124f291a7349
https://github.com/a13xp0p0v/kernel-hardening-checker/commit/b882a2b6c72b711159a73cc1bba82d1da6bc19c8

Please rebase onto the fresh `master`. You can use the new `perform_checking()` function.

Thanks!

**Comment by jvoisin** [comment]
Superseded by #163

**Pull request closed without merging**
