### PR TITLE
implementation of `arch_mmap_rnd` checks

### PR DESCRIPTION
**Pull request by d1sgr4c3**
reffering to #146, i implemented this cheks
we cant check maximum and minimum random offets through `sysctl` (please, see [my comments here](https://github.com/a13xp0p0v/kernel-hardening-checker/issues/146))

### CODE REVIEW

**Comment by a13xp0p0v** [comment]
Hello @d1sgr4c3, 

Thanks for your work!

I would recommend to leave `override_expected_value()` in `engine.py`, it will be needed for #50.

How about adding `refine_check(mode, checklist, parsed_options, target, source)` in `__init__.py`?

**Comment by d1sgr4c3** [comment]
sure, @a13xp0p0v 
that is easy. w8 for commit please, i think ill done with a few hours

**Comment by d1sgr4c3** [comment]
i re-created my branch, take a look pleasde

**Comment by a13xp0p0v** [comment]
Hello @d1sgr4c3,

I've improved your pull request a bit: dropped some code, improved code style and fixed a mistake.

Now it's merged! 

Thanks for your work!

**Pull request merged**
