### PR TITLE
Unitest addons

### PR DESCRIPTION
**Pull request by Willenst**
Hello, some new unittest code for #145 , now it must must cover almost 100%! I've added tests for `print_unknown_options()` and `colorize_result()`. Also, I had an interesting experience with _object-oriented programming, pylint, mypy, and unittest_, which are all new to me, hope everything works fine. Waiting for your feedback!

### CODE REVIEW

**Comment by a13xp0p0v** [comment]
@Willenst, thanks a lot for your work!

I've added some fixes to this PR.
Please check them one by one. Feel free to squash them into your version.

Thanks!

**Comment by Willenst** [comment]
@a13xp0p0v, thanks a lot for your fixes, good additions with a great code practice, I've learned a lot! 
All commits were squashed for a beautiful push request, so, just in case, they will be stored for some time here
https://github.com/Willenst/kernel-hardening-checker/tree/test_CI

Also, I've made a littler code refactor of my print_unknown_options (1-st commit), so it will be nice if you check it again.

Since you've said that additional debug info is unneeded in one of your additions (_unittest_ prints all the info if test fails), debug info from `run_engine` was also deleted.

**Comment by a13xp0p0v** [comment]
Excellent, thanks @Willenst.
Merged.

**Comment by a13xp0p0v** [comment]
I added one more test to cover this:
image

The details: https://app.codecov.io/gh/a13xp0p0v/kernel-hardening-checker/blob/master/kernel_hardening_checker%2Fengine.py?flags%5B0%5D=engine_unit-test

The commit: https://github.com/a13xp0p0v/kernel-hardening-checker/commit/f866b3686068ada2556aa773d6c06c691e2df9ad

**Pull request merged**
